@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mail;

import javax.annotation.ParametersAreNonnullByDefault;

import mail.core.utils.FieldsAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;