@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mail.plugins;

import javax.annotation.ParametersAreNonnullByDefault;

import mail.core.utils.FieldsAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;